# Generated by Django 2.2.2 on 2019-12-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20191217_1127'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cronjob',
            table='cron_jobs',
        ),
        migrations.AlterModelTable(
            name='repeatablejob',
            table='repeatable_jobs',
        ),
        migrations.AlterModelTable(
            name='scheduledjob',
            table='scheduled_jobs',
        ),
    ]
