# Generated by Django 2.2.2 on 2020-01-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='queue',
            field=models.CharField(max_length=64, verbose_name='queue'),
        ),
        migrations.AlterField(
            model_name='repeatablejob',
            name='queue',
            field=models.CharField(max_length=64, verbose_name='queue'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='queue',
            field=models.CharField(max_length=64, verbose_name='queue'),
        ),
    ]
